name: ESLint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  eslint:
    name: Validate Linting
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install ESLint
        run: bun install --frozen-lockfile
          
      - name: Run ESLint
        run: bunx eslint . --config eslint.config.mjs --fix

