name: ESLint Check

on:
  push:
    branches:
        - dev
        - main
  pull_request:
    branches: 
        - dev
        - main
  workflow_dispatch:

jobs:
  eslint:
    name: Validate Linting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install ESLint
        run: bun install
          
      - name: Run ESLint
        run: bunx eslint . --config eslint.config.mjs --fix

      - name: Commit Back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bun Install and Eslint Fix
          commit_options: "--no-verify --signoff"

