name: ESLint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  eslint:
    name: Validate Linting
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install ESLint
        run: npm ci
          
      - name: Run ESLint
        run: npx eslint . --config eslint.config.mjs --fix

