name: Make Code Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    name: Prettify code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prettify Code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md,json}
