name: Code Quality

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: bun install
          
      - name: Run Biome
        if: github.event_name == 'pull_request'
        run: biome ci .
        
      - name: Apply Biome
        if: github.event_name == 'push'
        run: biome check --write --unsafe .
        
      - name: Commit Back
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Biome Code Quality Update
          commit_options: "--no-verify --signoff"

      - name: Apply Changes to Dev Server
        if: github.event_name == 'push' && github.ref_name == 'dev'
        run: curl localhost:10000