name: Code Quality

on:
  push:
    branches: [main, dev]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
        
      - name: Apply Biome
        run: biome check --write --unsafe .
        
      - name: Commit Back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Biome Code Quality Update
          commit_options: "--no-verify --signoff"

  apply:
    runs-on: self-hosted
    needs: [quality]
    if: github.ref_name == 'dev'
    steps:
      - name: Apply Changes to Dev Server
        run: curl localhost:10000