name: Code Quality

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependancies
        run: bun i
      
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          
      - name: Run Biome
        if: github.event_name == 'pull_request'
        run: biome ci .
        
      - name: Apply Biome
        if: github.event_name == 'push'
        run: biome check --write --unsafe .
        
      - name: Commit Back
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Biome Code Quality Update
          commit_options: "--no-verify --signoff"
