name: ESLint and Prettier Check

on:
  push:
    branches:
        - dev
        - main
  pull_request:
    branches: 
        - dev
        - main
  workflow_dispatch:

jobs:
  lint-and-format:
    name: Validate Linting and Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
          
      - name: Run ESLint
        run: bun run lint:fix

      - name: Commit Back
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Prettified Code!
          commit_options: "--no-verify --signoff"

  update_docs:
    name: Update Documentation
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Generate Documentation
        run: bun run docs

      - name: Deploy on Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs --project-name=''
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

